In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
# Load the provided dataset
df = pd.read_csv('/content/drive/MyDrive/ML/L-2/sample_dataset_1000.csv')

In [ ]:
df.head()

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
0,1,Paul,25,Female,90041.86,2017-01-31,False,Creative
1,2,Paul,31,Male,90285.02,2019-05-29,False,Needs Improvement
2,3,Rachel,30,Male,84321.65,2022-12-14,False,Hardworking
3,4,Bob,45,Male,68189.99,2023-09-05,True,Fast Learner
4,5,Eve,34,Male,35428.35,2018-05-19,True,Dedicated

In [ ]:
# Display basic information
print("Data types of each column:")
print(df.dtypes)

Data types of each column:
ID                int64
Name             object
Age               int64
Gender           object
Salary          float64
Joining Date     object
Is Active          bool
Comments         object
dtype: object

Columns:
ID (Integer)
Name (Text)
Age (Numerical)
Gender (Categorical)
Salary (Float)
Joining Date (Datetime)
Is Active (Boolean)
Comments (Text)

In [ ]:
df.shape

(1000, 8)

In [ ]:
x=df[['Salary']] #Here [[ ]] means we are returning datafram
x.shape

(1000, 1)

In [ ]:
x=df['Salary'] #single bracket means we arer returning series
type(x)

pandas.core.series.Series

In [ ]:
#You can also assign different columns
newvar=df[['Joining Date']]
newvar

    Joining Date
0     2017-01-31
1     2019-05-29
2     2022-12-14
3     2023-09-05
4     2018-05-19
..           ...
995   2020-01-18
996   2023-11-22
997   2023-05-30
998   2017-08-15
999   2015-12-02

[1000 rows x 1 columns]

In [ ]:
y=df[['Joining Date','Salary']]
y

    Joining Date    Salary
0     2017-01-31  90041.86
1     2019-05-29  90285.02
2     2022-12-14  84321.65
3     2023-09-05  68189.99
4     2018-05-19  35428.35
..           ...       ...
995   2020-01-18  34288.04
996   2023-11-22  97404.78
997   2023-05-30  51242.03
998   2017-08-15  34117.08
999   2015-12-02  43198.50

[1000 rows x 2 columns]

In [ ]:
q=df[['Joining Date','Salary']]
q

    Joining Date    Salary
0     2017-01-31  90041.86
1     2019-05-29  90285.02
2     2022-12-14  84321.65
3     2023-09-05  68189.99
4     2018-05-19  35428.35
..           ...       ...
995   2020-01-18  34288.04
996   2023-11-22  97404.78
997   2023-05-30  51242.03
998   2017-08-15  34117.08
999   2015-12-02  43198.50

[1000 rows x 2 columns]

In [ ]:
#df.iloc[:]
#df.iloc[:2]
#df.iloc[0,0:2]
#indexing is like this [start:end:step]
df.iloc[:5,:5] # here [row indexing,column indexing] comma seperates row and columns

   ID    Name  Age  Gender    Salary
0   1    Paul   25  Female  90041.86
1   2    Paul   31    Male  90285.02
2   3  Rachel   30    Male  84321.65
3   4     Bob   45    Male  68189.99
4   5     Eve   34    Male  35428.35

In [ ]:
df.iloc[0:2,0:6]

   ID  Name  Age  Gender    Salary Joining Date
0   1  Paul   25  Female  90041.86   2017-01-31
1   2  Paul   31    Male  90285.02   2019-05-29

In [ ]:
df.loc[0:2,['Joining Date','Salary']]

  Joining Date    Salary
0   2017-01-31  90041.86
1   2019-05-29  90285.02
2   2022-12-14  84321.65

In [ ]:
df.loc[4:6]

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
4,5,Eve,34,Male,35428.35,2018-05-19,True,Dedicated
5,6,Hannah,23,Other,33952.28,2021-02-02,False,Fast Learner
6,7,Oscar,23,Female,72692.50,2021-04-02,False,Needs Improvement

In [ ]:
df.iloc[3:7]

,ID,Name,Age,Gender,Salary,Joining Date,Is Active,Comments
3,4,Bob,45,Male,68189.99,2023-09-05,True,Fast Learner
4,5,Eve,34,Male,35428.35,2018-05-19,True,Dedicated
5,6,Hannah,23,Other,33952.28,2021-02-02,False,Fast Learner
6,7,Oscar,23,Female,72692.50,2021-04-02,False,Needs Improvement

In [ ]:
df.iloc[5:,:4]

       ID    Name  Age  Gender
5       6  Hannah   23   Other
6       7   Oscar   23  Female
7       8    Tina   37   Other
8       9   Steve   22    Male
9      10   Frank   31   Other
..    ...     ...  ...     ...
995   996    Jack   58    Male
996   997    Jack   46   Other
997   998   Kathy   53    Male
998   999    Mona   48   Other
999  1000  Rachel   45  Female

[995 rows x 4 columns]

In [ ]:
df.dtypes

ID                   int64
Name                object
Age                  int64
Gender              object
Salary             float64
Joining Date        object
Is Active             bool
Comments            object
resvised_Salary    float64
dtype: object

In [ ]:
df.describe()

                ID          Age         Salary  resvised_Salary
count  1000.000000  1000.000000    1000.000000      1000.000000
mean    500.500000    40.923000   75042.559440     75042.559440
std     288.819436    11.771476   25839.572122     25839.572122
min       1.000000    20.000000   30023.460000     30023.460000
25%     250.750000    31.000000   52202.320000     52202.320000
50%     500.500000    42.000000   75955.130000     75955.130000
75%     750.250000    51.000000   96660.315000     96660.315000
max    1000.000000    60.000000  119880.780000    119880.780000